name: Self test

on:
  pull_request: ~

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./
        with:
          body: |
            Test upsert-comment from within!
            
            _Signed with love._
          matches: '.*_Signed with love\._$'
      - name: Show outputs
        run: |
          echo "comment ID is: ${{ steps.action.outputs.comment-id }}"
