name: Self Test

on:
  pull_request: ~
  push: ~

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'pull_request' }}
        name: Post PR comment from pull request event
        id: pr-action
        uses: ./
        with:
          body: |
            Test upsert-comment from PR!
            
            _Signed with love._
          matches: '.*_Signed with love\._$'
      - if: ${{ github.event_name == 'pull_request' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.pr-action.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - if: ${{ github.event_name == 'push' }}
        id: get-current-pr
        uses: infra-blocks/get-current-pull-request-action@v1
      - if: ${{ github.event_name == 'push' }}
        name: Post PR comment from push event
        id: push-action
        uses: ./
        with:
          body: |
            Test upsert-comment from push!

            __Signed with hatred.__
          matches: '.*__Signed with hatred\.__$'
          issue-number: ${{ steps.get-current-pr.outputs.number }}
      - if: ${{ github.event_name == 'push' }}
        name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.push-action.outputs) }}
        run: |
          echo "${OUTPUTS}"
